# Generated by Django 4.1 on 2022-09-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('anio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('caratula', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('noCapitulos', models.IntegerField()),
                ('anio', models.ImageField(upload_to='')),
                ('descripcion', models.TextField()),
                ('caratula', models.ImageField(upload_to='')),
            ],
        ),
    ]
