# Generated by Django 4.1 on 2022-09-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelisyseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='myimg'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='caratula',
            field=models.ImageField(blank=True, null=True, upload_to='myimg'),
        ),
    ]
