# Generated by Django 4.1 on 2022-09-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelisyseries', '0002_alter_pelicula_caratula_alter_serie_caratula'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='genero',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='anio',
            field=models.IntegerField(),
        ),
    ]
