# Generated by Django 4.1 on 2022-09-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelisyseries', '0003_pelicula_genero_serie_genero_alter_serie_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='estreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serie',
            name='estreno',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serie',
            name='anio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
