# Generated by Django 4.1 on 2022-10-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelisyseries', '0004_pelicula_estreno_serie_estreno_alter_pelicula_anio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('estreno', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('video', models.IntegerField(blank=True, default=1, null=True)),
                ('caratula', models.ImageField(blank=True, null=True, upload_to='myimg')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('genero', models.CharField(blank=True, max_length=255, null=True)),
                ('anio', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
        migrations.DeleteModel(
            name='Serie',
        ),
    ]
