# Generated by Django 4.1 on 2022-11-05 07:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pelisyseries', '0008_remove_contenido_nomegusta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido',
            name='favoritos',
            field=models.ManyToManyField(related_name='favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
